### PR TITLE
Update to Jammy 22.04

### PR DESCRIPTION
**Pull request by neonphog**
Updates the base to jammy 22.04.

I've made the following changes to packages (let me know if I missed anything) and attempted to describe my logic for the changes:

EDIT: The text comments are a bit out of date, pay more attention to the icons:

- :heavy_check_mark: - updated
- :x: - removed
- :recycle: - was in initial commit - safe to remove
- :seedling: - I think these packages just ended up getting carried forward as version upgrades from the beginning, so okay to remove?
- :wrench: - These were added in this commit - [update the linux build environment to reflect docs.rs](https://github.com/rust-lang/crates-build-env/commit/b9f9b09bc1fcf50e7c5d4dd1da56765153306b64) - okay to remove?
- :interrobang: - ask initial author if it's okay to remove

---

- [x] :x: :seedling: `clang-6.0` - the default clang in jammy is 14, the earliest available is 11, recommend leaving this out until a PR is made.
- [x] :x: :recycle: `enchant` - enchant has been removed. `enchant-2` is available, but recommend leaving this out until a PR is made.
- [x] :x: :recycle: `lib32gcc1` - this has been removed. There are other `lib32gcc-*` support packages, but recommend leaving this out until a PR is made.
- [x] :x: :interrobang:  `libappindicator3-dev` - *conflict with `libayatana-appindicator3-dev`* - *looks* like libappindicator is deprecated, so not including this as it conflicts with libayatana-appindacator.
- [x] :heavy_check_mark: `libarmadillo9` - updated to libarmadillo10
- [x] :x: :recycle: `libavresample-dev` - removed, recommend leaving out.
- [x] :x: :recycle: `libavresample4` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libayatana-appindicator3-dev` - *conflict with `libappindicator3-dev`* - resolved conflict by not including the other `libappindicator3-dev` as that appears to be deprecated.
- [x] :heavy_check_mark: `libboost-filesystem1.67.0` - update to 1.74.0
- [x] :heavy_check_mark: `libboost-filesystem1.71.0` - update to 1.74.0
- [x] :heavy_check_mark: `libboost-iostreams1.67.0` - update to 1.74.0
- [x] :heavy_check_mark: `libboost-iostreams1.71.0` - update to 1.74.0
- [x] :heavy_check_mark: `libboost-system1.67.0` - update to 1.74.0
- [x] :heavy_check_mark: `libboost-system1.71.0` - update to 1.74.0
- [x] :heavy_check_mark: `libcapnp-0.7.0` - update to 0.8.0
- [x] :heavy_check_mark: `libcapstone3` - update to libcapstone4
- [x] :heavy_check_mark: `libcdio18` - update to libcdio19
- [x] :heavy_check_mark: `libcfitsio8` - update to libcfitsio9
- [x] :x: :recycle: `libcilkrts5` - removed, recommend leaving out.
- [x] :x: :seedling: `libclang-6.0-dev` - see `clang-6.0`
- [x] :x: :seedling: `libclang-common-6.0-dev` - see `clang-6.0`
- [x] :x: :seedling: `libclang1-6.0` - see `clang-6.0`
- [x] :x: :recycle: `libcroco3` - removed, recommend leaving out.
- [x] :x: :wrench: `libcroco3-dev` - removed, recommend leaving out.
- [x] :x: :recycle: `libcrystalhd3` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libdap25` - update to libdap27
- [x] :heavy_check_mark: `libdc1394-22` - update to libdc1394-25
- [x] :heavy_check_mark: `libdns-export1109` - update to libdns-export1110
- [x] :heavy_check_mark: `libdns1109` - update to libdns1110
- [x] :x: :recycle: `libenchant1c2a` - see `enchant`
- [x] :x: :wrench: `libepsilon1` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libgc1c2` - use libgc1 instead.
- [x] :heavy_check_mark: `libgdal26` - update to libgdal30
- [x] :heavy_check_mark: `libgeos-3.8.0` - update to libgeos3.10.2
- [x] :heavy_check_mark: `libglew2.1` - update to libglew2.2
- [x] :heavy_check_mark: `libhogweed5` - update to libhogweed6
- [x] :heavy_check_mark: `libicu66` - update to libicu70
- [x] :heavy_check_mark: `libidn11` - update to libidn12
- [x] :heavy_check_mark: `libilmbase24` - update to libilmbase25
- [x] :heavy_check_mark: `libisl22` - update to libisl23
- [x] :heavy_check_mark: `libjson-c4` - update to libjson-c5
- [x] :heavy_check_mark: `libjsoncpp1` - update to libjsoncpp25
- [x] :heavy_check_mark: `libkadm5clnt-mit11` - update to libkadm mit12
- [x] :heavy_check_mark: `libkadm5srv-mit11` - update to libkadm mit12
- [x] :heavy_check_mark: `libkdb5-9` - update to libkdb5-10
- [x] :heavy_check_mark: `libldap-2.4-2` - update to libldap-2.5-0
- [x] :x: :seedling: `libllvm6.0` - see `clang-6.0`
- [x] :x: :seedling: `libllvm7` - see `clang-6.0`
- [x] :x: :seedling: `libllvm8` - see `clang-6.0`
- [x] :heavy_check_mark: `libmariadbclient-dev` - now provided by `libmariadb-dev`
- [x] :heavy_check_mark: `libmariadbclient-dev-compat` - now provided by `libmariadb-dev-compat`
- [x] :x: :wrench: `libmirclient-dev` - removed, recommend leaving out.
- [x] :x: :wrench: `libmirclient9` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libmircommon7` - updated to libmircommon8.
- [x] :x: :wrench: `libmirprotobuf3` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libmpdec2` - update to libmpdec3
- [x] :x: :recycle: `libmpx2` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libnetcdf15` - update to libnetcdf19
- [x] :heavy_check_mark: `libnettle7` - update to libnettle8
- [x] :heavy_check_mark: `libopencv-calib3d4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-contrib4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-core4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-features2d4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-flann4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-highgui4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-imgcodecs4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-imgproc4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-ml4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-objdetect4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-photo4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-shape4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-stitching4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-superres4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-video4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-videoio4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-videostab4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv-viz4.2` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv4.2-java` - update to libopencv4.5
- [x] :heavy_check_mark: `libopencv4.2-jni` - update to libopencv4.5
- [x] :heavy_check_mark: `libopenexr24` - update to libopenexr25
- [x] :x: :recycle: `libparse-debianchangelog-perl` - removed, recommend leaving out.
- [x] :heavy_check_mark: `libperl5.30` - update to libperl5.34
- [x] :heavy_check_mark: `libpgm-5.2-0` - update to libpgm-5.30-0
- [x] :heavy_check_mark: `libpoppler97` - update to libpoppler118
- [x] :heavy_check_mark: `libproj15` - update to libproj22
- [x] :heavy_check_mark: `libprotobuf-lite17` - update to libprotobuf-lite23
- [x] :heavy_check_mark: `libprotobuf17` - update to libprotobuf23
- [x] :heavy_check_mark: `libprotoc17` - update to libprotoc23
- [x] :heavy_check_mark: `libpython3.9` - update to libpython3.10
- [x] :heavy_check_mark: `libpython3.9-dev` - update to libpython3.10
- [x] :heavy_check_mark: `libpython3.9-minimal` - update to libpython3.10
- [x] :heavy_check_mark: `libpython3.9-stdlib` - update to libpython3.10
- [x] :heavy_check_mark: `libqhull7` - update to libqhull8.0
- [x] :x: :seedling: `libruby2.7` - jammy only has ruby3.0
- [x] :heavy_check_mark: `libsemanage1` - update to libsemanage2
- [x] :heavy_check_mark: `libsepol1` - update to libsepol2
- [x] :heavy_check_mark: `libsepol1-dev` - covered by libsepol-dev
- [x] :heavy_check_mark: `libssl1.1` - update to libssl3
- [x] :heavy_check_mark: `libubsan0` - update to libubsan1
- [x] :heavy_check_mark: `libvpx6` - update to libvpx7
- [x] :heavy_check_mark: `libvtk6.3` - update to libvtk9.1
- [x] :heavy_check_mark: `libwacom2` - update to update to libwacom9
- [x] :heavy_check_mark: `libwebp6` - update to libwebp7
- [x] :heavy_check_mark: `libx264-155` - update to libx264-163
- [x] :heavy_check_mark: `libx265-179` - update to libx265-199
- [x] :heavy_check_mark: `python-dev` - replaced by explicit python2-dev
- [x] :x: :recycle: `qt5-default` - no longer required
- [x] :x: :seedling: `ruby2.7` - jammy only has ruby3.0
- [x] :x: :seedling: `ruby2.7-dev` - jammy only has ruby3.0

### CODE REVIEW

**Comment by neonphog** [comment]
@syphar - I believe this is ready for review when you get a chance.

**Comment by neonphog** [comment]
@FantasyTeddy - You previously added [Add libappindicator3-dev package for libappindicator-sys crate](https://github.com/rust-lang/crates-build-env/pull/59) to the crates-build-env. Since then, [Add packages necessary for libayatana-appindicator-sys to compile](https://github.com/rust-lang/crates-build-env/pull/81) has also been added.

When updating to Ubuntu Jammy 22.04, these crates now conflict and cannot be installed together. It also looks like libappindicator is deprecated.

Do you have any concerns or comments about libappindicator being removed from the crates-build-env?

Thanks!

**Comment by neonphog** [comment]
@jyn514 - I've divided up the removed packages into three categories, and added some icons to the PR description, I don't use my git forensics skills very often, so hopefully I got everything correct:

:seedling: - these packages seemed to start out with version numbers early on, and were upgraded as changes were made, and non-versioned package references were added. It's possible some folks are depending on these, but there was no explicit add PR, so maybe it's okay to remove them?

:wrench: - these packages were added in a specific commit to [update the linux build environment to reflect docs.rs](https://github.com/rust-lang/crates-build-env/commit/b9f9b09bc1fcf50e7c5d4dd1da56765153306b64)... but they no longer exist in jammy, and again, were not added by an explicit PR, so okay to remove them?

:interrobang: - the only package that has been removed in this PR that was explicitly added by a community member is the libappindicator. I've posted a message here to the author asking if that removal is okay.

Let me know if you think anything is amiss here, or if there's anything else I can do to help move this along. Thanks!

**Comment by neonphog** [comment]
Oh, I guess there's also the fourth category :recycle: of items that were in the initial commit that you indicated should be safe to remove.

**Comment by FantasyTeddy** [comment]
I have not worked with the libappindicator-sys crate since I made the PR for adding the libappindicator3-dev package.
Therefore, I cannot really give an educated answer.

I would suggest to remove the package and see if someone notices.

**Comment by jyn514** [comment]
> 

cc @qdot, you're listed as the crate owner of `libappindicator-sys`.

**Comment by qdot** [comment]
@jyn514 I handed off libappindicated-sys to the tauri project a couple of years ago, they're the ones you'd want to contact about any updates/changes needed.

**Comment by jyn514** [comment]
not sure who on https://github.com/orgs/tauri-apps/people is in a leadership position, so just going to roll the dice ... @amrbashir

> FantasyTeddy - You previously added [Add libappindicator3-dev package for libappindicator-sys crate](https://github.com/rust-lang/crates-build-env/pull/59) to the crates-build-env. Since then, [Add packages necessary for libayatana-appindicator-sys to compile](https://github.com/rust-lang/crates-build-env/pull/81) has also been added.

> When updating to Ubuntu Jammy 22.04, these crates now conflict and cannot be installed together. It also looks like libappindicator is deprecated.

> Do you have any concerns or comments about libappindicator being removed from the crates-build-env?

> Thanks!

**Review by jyn514 — APPROVED** [review]

**Comment by amrbashir** [comment]
As @neonphog found, we do support both libs so it should be fine for us👍.

**Pull request merged**
