### PR TITLE
add fortran to build environment

### PR DESCRIPTION
**Pull request by jyn514**
closes https://github.com/rust-lang/docs.rs/issues/483

### CODE REVIEW

**Comment by jyn514** [comment]
@pietroalbini  do you know why CI is failing? It doesn't seem to be related to this change.

**Comment by pietroalbini** [comment]
@jyn514 pushed a commit to actually show the diff when linting fails:

```diff
--- /tmp/sorted-packages.txt    2019-12-09 09:35:25.812465059 +0100
+++ packages.txt        2019-12-09 09:34:54.064944260 +0100
@@ -23,8 +23,8 @@
 dselect
 emacsen-common
 enchant
-gfortran
 git
+gfortran
 gnupg
 golang
 gstreamer1.0-plugins-base
```

Also pushed another commit to fix the lint.

**Comment by jyn514** [comment]
It looks like the version of diff on Travis doesn't have a --color option:
https://travis-ci.com/rust-lang/crates-build-env/jobs/265107590#L461

**Comment by jyn514** [comment]
LGTM, is this waiting on anything?

**Pull request merged**
