### PR TITLE
Added required packages 'libtss2-dev' and 'libjson-c-dev'.

### PR DESCRIPTION
**Pull request by dEajL3kA**
Please consider adding these packages as they are required to build our project. Thank you!

### CODE REVIEW

**Review by syphar — APPROVED** [review]

**Comment by syphar** [comment]
thanks! 

please not that it can take some hours (to half a day if I recall correctly) until docs.rs is actually using the image for new builds

**Comment by dEajL3kA** [comment]
Thanks 🥳

**Comment by dEajL3kA** [comment]
> please not that it can take some hours (to half a day if I recall correctly) until docs.rs is actually using the image for new builds

Is there any way to check when Docs.rs starts using the new image?

After more than 24 hours (more like 32 hours) build still fails. Any my debug outputs verify that _libtss2_ isn't availbale. 

Log from Docs.rs:
```
[INFO] [stderr]   --- stderr
[INFO] [stderr]   [/usr/lib/x86_64-linux-gnu]
[INFO] [stderr] 
[INFO] [stderr]   [/usr/lib/x86_64-linux-gnu/pkgconfig]
[INFO] [stderr] 
[INFO] [stderr]   [pkg-config]
```

Log with the exactly same code from my onw build-env:
```
[INFO] [/usr/lib/x86_64-linux-gnu]
[INFO] libtss2-tcti-cmd.so.0.0.0
[INFO] libtss2-tcti-cmd.so
[INFO] libtss2-tcti-libtpms.so
[INFO] libtss2-tcti-libtpms.so.0
[INFO] libtss2-tcti-libtpms.so.0.0.0
[INFO] libtss2-tcti-mssim.so.0.0.0
[INFO] libtss2-esys.so.0.0.1
[INFO] libtss2-tcti-mssim.so
[INFO] libtss2-tcti-i2c-helper.so.0
[INFO] libtss2-fapi.so.1.0.0
[INFO] libtss2-mu.so.0
[INFO] libtss2-mu.so.0.0.1
[INFO] libtss2-policy.so.0
[INFO] libtss2-tcti-swtpm.so.0
[INFO] libtss2-sys.so.1.0.1
[INFO] libtss2-tctildr.so.0.0.0
[INFO] libtss2-tcti-spi-helper.so.0.0.0
[INFO] libtss2-tcti-i2c-ftdi.so.0
[INFO] libtss2-policy.so
[INFO] libtss2-tctildr.so
[INFO] libtss2-tcti-cmd.so.0
[INFO] libtss2-fapi.so
[INFO] libtss2-tcti-spi-ftdi.so.0
[INFO] libtss2-rc.so
[INFO] libtss2-esys.so
[INFO] libtss2-tcti-device.so
[INFO] libtss2-tcti-spidev.so.0.0.0
[INFO] libtss2-fapi.so.1
[INFO] libtss2-tcti-i2c-ftdi.so.0.0.0
[INFO] libtss2-policy.so.0.0.0
[INFO] libtss2-tctildr.so.0
[INFO] libtss2-tcti-pcap.so.0.0.0
[INFO] libtss2-tcti-swtpm.so
[INFO] libtss2-tcti-spi-helper.so
[INFO] libtss2-tcti-i2c-helper.so.0.0.0
[INFO] libtss2-tcti-spi-ltt2go.so.0.0.0
[INFO] libtss2-tcti-device.so.0.0.0
[INFO] libtss2-rc.so.0
[INFO] libtss2-tcti-spi-ftdi.so.0.0.0
[INFO] libtss2-tcti-spi-helper.so.0
[INFO] libtss2-sys.so.1
[INFO] libtss2-tcti-spi-ltt2go.so
[INFO] libtss2-mu.so
[INFO] libtss2-tcti-spidev.so.0
[INFO] libtss2-rc.so.0.0.0
[INFO] libtss2-sys.so
[INFO] libtss2-tcti-spidev.so
[INFO] libtss2-tcti-pcap.so.0
[INFO] libtss2-tcti-i2c-ftdi.so
[INFO] libtss2-tcti-spi-ltt2go.so.0
[INFO] libtss2-tcti-i2c-helper.so
[INFO] libtss2-tcti-pcap.so
[INFO] libtss2-tcti-mssim.so.0
[INFO] libtss2-tcti-device.so.0
[INFO] libtss2-tcti-swtpm.so.0.0.0
[INFO] libtss2-tcti-spi-ftdi.so
[INFO] libtss2-esys.so.0
[INFO] 
[INFO] [/usr/lib/x86_64-linux-gnu/pkgconfig]
[INFO] tss2-tcti-cmd.pc
[INFO] tss2-tcti-i2c-ftdi.pc
[INFO] tss2-tcti-pcap.pc
[INFO] tss2-tcti-spi-ftdi.pc
[INFO] tss2-tcti-swtpm.pc
[INFO] tss2-tcti-libtpms.pc
[INFO] tss2-rc.pc
[INFO] tss2-tcti-mssim.pc
[INFO] tss2-tcti-i2c-helper.pc
[INFO] tss2-tcti-device.pc
[INFO] tss2-tcti-spidev.pc
[INFO] tss2-sys.pc
[INFO] tss2-mu.pc
[INFO] tss2-fapi.pc
[INFO] tss2-esys.pc
[INFO] tss2-tcti-spi-helper.pc
[INFO] tss2-policy.pc
[INFO] tss2-tctildr.pc
[INFO] tss2-tcti-spi-ltt2go.pc
[INFO] 
[INFO] [pkg-config]
[INFO] tss2-tcti-cmd                  tss2-tcti-cmd - TCTI library for communicating with a subproccess that can communicate with the TPM.
[INFO] tss2-tcti-i2c-ftdi             tss2-tcti-i2c-ftdi - TCTI library for communicating with a TPM over USB-FTDI-I2C converter.
[INFO] tss2-tcti-pcap                 tss2-tcti-pcap - TCTI library for debugging at the TCTI interface.
[INFO] tss2-tcti-spi-ftdi             tss2-tcti-spi-ftdi - TCTI library for communicating with a TPM over USB-FTDI-SPI converter.
[INFO] tss2-tcti-swtpm                tss2-tcti-swtpm - TCTI library for communicating with swtpm.
[INFO] tss2-tcti-libtpms              tss2-tcti-libtpms - TCTI library for communicating with the libtpms library.
[INFO] tss2-rc                        tss2-rc - TPM2 error decoding library.
[INFO] tss2-tcti-mssim                tss2-tcti-mssim - TCTI library for communicating with the Microsoft TPM2 simulator.
[INFO] tss2-tcti-i2c-helper           tss2-tcti-i2c-helper - TCTI library for communicating with the TPM over I2C.
[INFO] tss2-tcti-device               tss2-tcti-device - TCTI library for communicating with a TPM device node.
[INFO] tss2-tcti-spidev               tss2-tcti-spidev - TCTI library for communicating with the TPM over spidev.
[INFO] tss2-sys                       tss2-sys - TPM2 System API library.
[INFO] tss2-mu                        tss2-mu - TPM2 type marshaling and unmarshaling library.
[INFO] tss2-fapi                      tss2-fapi - TPM2 Feature API library.
[INFO] tss2-esys                      tss2-esys - TPM2 Enhanced System API library.
[INFO] tss2-tcti-spi-helper           tss2-tcti-spi-helper - TCTI library for communicating with the TPM over SPI.
[INFO] tss2-policy                    tss2-policy - TPM2 policy library.
[INFO] tss2-tctildr                   tss2-tctildr - Library to simplify management of TCTIs.
[INFO] tss2-tcti-spi-ltt2go           tss2-tcti-spi-ltt2go - TCTI library for communicating with the LetsTrust-TPM2Go over USB.
```

**Comment by dEajL3kA** [comment]
As a follow up to https://github.com/rust-lang/crates-build-env/pull/154#issuecomment-2365322192, is it because this action failed?

https://github.com/rust-lang/crates-build-env/actions/runs/10959543961/job/30432134029

I don't think the error has anything to do with my PR :sweat_smile:

**Comment by syphar** [comment]
yep, it's because the CI workflow on master failed. I just retried it, let's see

**Comment by syphar** [comment]
hm.. seems to be a permission issue with the image upload (so you did everything right). 

I'm checking with the infra team: 
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/did.20github.20token.20permissions.20change.3F

**Comment by syphar** [comment]
@dEajL3kA the fix was merged in https://github.com/rust-lang/crates-build-env/pull/155 and images are published again. 

So in some hours, latest tomorrow you'll be able to do your builds.

**Comment by syphar** [comment]
I had an idea how to improve this: https://github.com/rust-lang/docs.rs/issues/2612

**Comment by dEajL3kA** [comment]
> @dEajL3kA the fix was merged in #155 and images are published again.
> 
> So in some hours, latest tomorrow you'll be able to do your builds.

Sorry, I have been away for a while. I can confirm that it is working now 🥳

**Pull request merged**
