### PR TITLE
linux: add linux-headers-generic

### PR DESCRIPTION
**Pull request by alexforster**
Needed to build my [libbpf-sys](https://github.com/alexforster/libbpf-sys) crate.

### CODE REVIEW

**Comment by jyn514** [comment]
@alexforster The changes are merged but the crate environment won't be updated until the docker image gets published and I restart the server. I can schedule a rebuild after that.

**Comment by alexforster** [comment]
Cool, no rush. Thanks!

**Comment by jyn514** [comment]
@alexforster [I rebuilt it](https://docs.rs/crate/libbpf-sys/0.0.6-3/builds/212955), but the build script trying to modify the source directory which isn't allowed in the sandbox. You'll have to fix that on your end. As an alternative, you could try writing to `OUT_DIR` (set by Cargo).

**Comment by alexforster** [comment]
Ah okay this is an easy fix. Thanks again, I really appreciate the responsiveness.

**Comment by jyn514** [comment]
No problem! I like helping with build failures, they're usually pretty simple to fix :)

By the way, the 'dependencies metadata' feature isn't broken, it was just never implemented, that's why it wasn't documented. We want to share the build environment with Crater so it looks like it probably won't ever be added, we should probably remove it internally at some point.

**Pull request merged**
