### PR TITLE
Add libavdevice* and libavfilter*

### PR DESCRIPTION
**Pull request by zmwangx**
The added packages are required to build ffmpeg-sys-next and ffmpeg-next.

https://docs.rs/crate/ffmpeg-sys-next/4.2.0/builds/256836
https://docs.rs/crate/ffmpeg-next/4.2.1/builds/256842

Also added an unrelated commit to remove duplicates from the package list... Doesn't really belong to this PR but I was following the [guide](https://forge.rust-lang.org/docs-rs/add-dependencies.html) which asks me to satisfy linters, so please excuse me.

### CODE REVIEW

**Comment by jyn514** [comment]
Thanks for the PR! Not sure how the duplicates slipped through but I appreciate you removing them.

**Comment by zmwangx** [comment]
@jyn514 Could you please also queue a rebuild for `ffmpeg-sys-next` 4.2.0? Thanks.

**Comment by jyn514** [comment]
Queued and rebuilt! https://docs.rs/crate/ffmpeg-sys-next/4.2.0

**Comment by zmwangx** [comment]
Cool, thanks again.

**Pull request merged**
